var graph = {
  "nodes": [
    {"id": "설국열차", "group": 1},

    {"id": "지구온난화", "group": 2},
	  {"id": "빙하기", "group": 2},
    {"id": "인류멸망", "group": 2},

    {"id": "윌포드의 기차", "group": 3},
    {"id": "엔진", "group": 3},
    {"id": "균형", "group": 3},
    {"id": "질서", "group": 3},
    {"id": "부품", "group": 3},
    {"id": "계급", "group": 3},
    {"id": "차별", "group": 3},
    {"id": "감시", "group": 3},

    {"id": "머리칸", "group": 4},
    {"id": "지배계급", "group": 4},
    {"id": "물공급칸", "group": 4},
    {"id": "식물칸", "group": 4},
    {"id": "수족관칸", "group": 4},
    {"id": "교실칸", "group": 4},
    {"id": "클럽칸", "group": 4},
    {"id": "찜질방칸", "group": 4},
    {"id": "손님칸", "group": 4},
    {"id": "미용실칸", "group": 4},
    {"id": "양복점칸", "group": 4},
    {"id": "레스토랑칸", "group": 4},
    {"id": "윌포드", "group": 4},
    {"id": "메이슨", "group": 4},
    {"id": "프랑코", "group": 4},
    {"id": "교사", "group": 4},

    {"id": "꼬리칸", "group": 5},
    {"id": "피지배계급", "group": 5},
    {"id": "빈곤", "group": 5},
    {"id": "단백질블록", "group": 5},
    {"id": "바퀴벌레", "group": 5},
    {"id": "반란", "group": 5},
    {"id": "커티스", "group": 5},
    {"id": "에드가", "group": 5},
    {"id": "길리엄", "group": 5},
    {"id": "타냐", "group": 5},
    {"id": "앤드류", "group": 5},
    {"id": "남궁민수", "group": 5},
    {"id": "요나", "group": 5},
    {"id": "크로놀", "group": 5}

  ],
  "links": [
    {"source": "설국열차", "target": "지구온난화", "value": 2},
    {"source": "지구온난화", "target": "빙하기", "value": 2},
    {"source": "지구온난화", "target": "인류멸망", "value": 2},

    {"source": "설국열차", "target": "윌포드의 기차", "value": 2},
    {"source": "윌포드의 기차", "target": "엔진", "value": 2},
    {"source": "윌포드의 기차", "target": "균형", "value": 2},
    {"source": "윌포드의 기차", "target": "질서", "value": 2},
    {"source": "윌포드의 기차", "target": "부품", "value": 2},
    {"source": "윌포드의 기차", "target": "계급", "value": 2},
    {"source": "윌포드의 기차", "target": "차별", "value": 2},
    {"source": "윌포드의 기차", "target": "감시", "value": 2},

    {"source": "설국열차", "target": "머리칸", "value": 2},
    {"source": "머리칸", "target": "지배계급", "value": 2},
    {"source": "머리칸", "target": "물공급칸", "value": 2},
    {"source": "머리칸", "target": "식물칸", "value": 2},
    {"source": "머리칸", "target": "수족관칸", "value": 2},
    {"source": "머리칸", "target": "교실칸", "value": 2},
    {"source": "머리칸", "target": "클럽칸", "value": 2},
    {"source": "머리칸", "target": "찜질방칸", "value": 2},
    {"source": "머리칸", "target": "손님칸", "value": 2},
    {"source": "머리칸", "target": "미용실칸", "value": 2},
    {"source": "머리칸", "target": "양복점칸", "value": 2},
    {"source": "머리칸", "target": "레스토랑칸", "value": 2},
    {"source": "지배계급", "target": "윌포드", "value": 2},
    {"source": "지배계급", "target": "메이슨", "value": 2},
    {"source": "지배계급", "target": "프랑코", "value": 2},
    {"source": "지배계급", "target": "교사", "value": 2},

    {"source": "설국열차", "target": "꼬리칸", "value": 2},
    {"source": "꼬리칸", "target": "피지배계급", "value": 2},
    {"source": "꼬리칸", "target": "빈곤", "value": 2},
    {"source": "꼬리칸", "target": "반란", "value": 2},
    {"source": "꼬리칸", "target": "단백질블록", "value": 2},
    {"source": "단백질블록", "target": "바퀴벌레", "value": 2},
    {"source": "꼬리칸", "target": "크로놀", "value": 2},
    {"source": "피지배계급", "target": "커티스", "value": 2},
    {"source": "피지배계급", "target": "에드가", "value": 2},
    {"source": "피지배계급", "target": "길리엄", "value": 2},
    {"source": "피지배계급", "target": "타냐", "value": 2},
    {"source": "피지배계급", "target": "앤드류", "value": 2},
    {"source": "피지배계급", "target": "남궁민수", "value": 2},
    {"source": "피지배계급", "target": "요나", "value": 2}

  ]
}
